config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/about'

    resources :clinics do
      member do
      post :create_doctor
      delete :destroy_doctor
    end
      resources :patients do
        member do
          post :create_doctor
          delete :destroy_doctor
          patch :wait_patient
          patch :to_doctor_patient
          patch :to_xray_patient
          patch :to_surgery_patient
          patch :to_pay_bill_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

end

app/models/clinic.rb
class Clinic < ActiveRecord::Base

  has_many :patients, dependent: :destroy
  has_many :doctors, as: :doctorable

  US_STATE_OPTIONS =
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  def index

    @clinics = if !params[:q].blank?
      Clinic.where("name LIKE ? OR st_address LIKE ? OR city LIKE ? OR state LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")

    else
    @clinics = Clinic.all

    end
  end

  def show
    @clinic = Clinic.find params[:id]
    @patients = @clinic.patients
    @doctor = Doctor.new
    # @doctors = @clinic.doctors
    @doctors = if !params[:q2].blank?
      @clinic.doctors.where("doctor_name LIKE ?", "%#{params[:q2]}%")
    else
      @clinic.doctors
    end
  end
  
  def new
    @clinic = Clinic.new
  end

  def create
    @clinic = Clinic.create my_params
    redirect_to clinics_path
  end

  def edit
    @clinic = Clinic.find params[:id]
  end

  def update
    @clinic = Clinic.find params[:id]
    @clinic.update my_params
    redirect_to clinic_path(@clinic)
  end

  def destroy
    @clinic = Clinic.find params[:id]
    @clinic.destroy
    redirect_to clinics_path
  end

  def create_doctor
    @clinic = Clinic.find params[:id]
    @doctor = @clinic.doctors.create doctor_params
    redirect_to clinic_path(@clinic)
  end

  def destroy_doctor
    # @clinic = Clinic.find params[:id]
    @doctor = Doctor.find params[:id]
    @doctor.destroy
    redirect_to @doctor.doctorable
  end

private
  def my_params
    params.require(:clinic).permit(
      :name,
      :st_address,
      :city,
      :state
    )
  end

  def set_clinic
    @clinic = Clinic.find params[:id]
  end

  def doctor_params
    params.require(:doctor).permit(
      :doctor_name
      )
  end

end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.haml
.text-center
  .list-group-item
    = form_for @clinic do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :st_address
        = f.text_field :st_address, class: "form-control"
      .form-group
        = f.label :city
        = f.text_field :city, class: "form-control"
      .form-group
        = f.label :state
        = f.select :state, options_for_select(Clinic::US_STATE_OPTIONS, f.object.state), include_blank: "----Select State___"
      %br
        = f.submit "Submit", class: "btn btn-primary"
    %br

app/views/clinics/edit.html.haml
.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              Edit Clinic Information
        = link_to "Cancel and Return to Clinic", clinic_path(@clinic)

    =render 'form'

app/views/clinics/index.html.haml
= form_tag clinics_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Clinics"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %i.glyphicon.glyphicon-search


.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              Clinics
            %br
          = link_to "Add New Clinic", new_clinic_path
          %br
/ %p{class: "text-left"}
.row
  - @clinics.each do |clinic|
    .col-md-4.text-center
      .list-group-item
        %strong
          Clinic Name:
        = link_to clinic.name, clinic_path(clinic)
        %br
        = link_to "Edit Clinic", edit_clinic_path(clinic)
        |
        = link_to "Delete Clinic", clinic_path(clinic), method: :delete
      %br

app/views/clinics/new.html.erb
<center>
  <h1>
    <strong>
      <u>
        Add Information for New Clinic
      </u>
    </strong>
  </h1>
  <%= render 'form' %></div></div></div>
</center>

app/views/clinics/show.html.haml
%p#notice=notice
.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              =@clinic.name
          = @clinic.st_address
          %br/
          = @clinic.city + ", "
          = @clinic.state
          %br
          %br
          = link_to "Edit Clinic", edit_clinic_path(@clinic)
          |
          = link_to "Delete Clinic", clinic_path(@clinic), method: :delete
          %br
          = link_to "Return to Clinics", clinics_path
          |
          = link_to "Return to Main", root_path
  %div.col-md-4.col-md-offset-4
    .list-group-item
      .text-center
        %strong
          %u
            %h4
              Patients: 
        = link_to "View Patient Index", clinic_patients_path(@clinic, @patients)
        |
        = link_to "Add Patient", new_clinic_patient_path(@clinic)
      %ul
      - @patients.each do |patient|
        %li
          = link_to patient.last_name + ", " + patient.first_name, clinic_patient_path(@clinic, patient)
          = '|'
          = workflow_state_helper(patient)
    %br
    .list-group-item
      .text-center
        %strong Clinic Doctors:
        %br
        = form_tag clinic_path(@clinic), method: :get, class: "navbar-form", role: "search" do
          .input-group
            = text_field_tag 'q2', params[:q2], class: "form-control", id: "srch-term", placeholder: "Search Doctors"
            .input-group-btn
              %button.btn.btn-default{:style => "width:40px;"}
                %i.glyphicon.glyphicon-search
        %br
        - @doctors.each do |doctor|
          = doctor.doctor_name
          = link_to "Delete Doctor", destroy_doctor_clinic_path(doctor), method: :delete
          %br
        = form_for @doctor, url: create_doctor_clinic_path(@clinic) do |f|
          .form_group
            = f.label :doctor_name
            = f.text_field :doctor_name, class: "form-control"
            %br/
          = f.submit "Add Doctor", class: "btn btn-primary"