config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/about'

    resources :clinics do
      member do
      post :create_doctor
      delete :destroy_doctor
    end
      resources :patients do
        member do
          post :create_doctor
          delete :destroy_doctor
          patch :wait_patient
          patch :to_doctor_patient
          patch :to_xray_patient
          patch :to_surgery_patient
          patch :to_pay_bill_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

end

app/models/medication.rb
class Medication < ActiveRecord::Base
  has_many :patient_medications
  has_many :patients, through: :patient_medications


  def has_generic?
    if self.generic_option == true
      "yes"
    else
      "no"
    end
  end


end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController

  def index
    @medications = if !params[:q].blank?
      Medication.where("name LIKE ? OR company LIKE ? OR adverse_reactions LIKE ? OR generic_option LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
    @medications = Medication.all
    end
  end

  def show
    @medication = Medication.find params[:id]
    @patients = @medication.patients
  end

    # @clinic = Clinic.find params[:clinic_id]
    # @patient = @clinic.patients.find params[:patient_id]
    # @medication = @patient.medications.new


  def new
    @medication = Medication.new
    @patients = Patient.all
  end

  def create
    @medication = Medication.create medication_params
    redirect_to medications_path
  end

  def edit
    @medication = Medication.find params[:id]
    @patients = Patient.all
  end

  def update
    @medication = Medication.find params[:id]
    @medication.update medication_params
    redirect_to medication_path(@medication)
  end

  def destroy
    @medication = Medication.find params[:id]
    @medication.delete
    redirect_to medications_path
  end


private
  def medication_params
    params.require(:medication).permit(
      :name,
      :company,
      :adverse_reactions,
      :generic_option,
      patient_ids: []
      )
  end

  def set_patient
    @patient = Patient.find params[:id]
  end

end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/views/medications/_form.html.erb
.list-group-item
<%= form_for [@medication] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :company %>
  <%= f.text_field :company %>
  <br>
  <%= f.label :adverse_reactions %>
  <%= f.text_area :adverse_reactions %>
  <br>
  <%= f.label :generic_option %>
  <%= f.radio_button(:generic_option, 1) %>
  <%= f.label(:generic_option, "yes") %>
  <%= f.radio_button(:generic_option, 0) %>
  <%= f.label(:generic_option, "no") %>
  <br>

  <br>
  <% @patients.each do |patient| %>
    <%= check_box_tag 'medication[patient_ids][]', patient.id, @medication.patients.include?(patient) %>
    <%= patient.last_name %>
    <br>
 <% end %>
  <br>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "Cancel", medications_path %>
|
<%= link_to "Return to Main", root_path %>

app/views/medications/_form.html.haml
.list-group-item.text-center
  =form_for [@medication] do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: "form-control"
    .form-group
      = f.label :company
      = f.text_field :company, class: "form-control"
    .form-group
      = f.label :adverse_reactions
      = f.text_area :adverse_reactions, class: "form-control"
    .list-group-item
      = f.label :generic_option
      = f.radio_button(:generic_option, 1)
      = f.label(:generic_option, "yes")
      = f.radio_button(:generic_option, 0)
      = f.label(:generic_option, "no")
    %br
    .list-group-item
      %strong
        = "Patients users:"
      .text-left
        .checkbox
          - @patients.each do |patient|
            %label
              = check_box_tag 'medication[patient_ids][]', patient.id, @medication.patients.include?(patient)
              = patient.last_name
            %br
    %br
    = f.submit "Submit", class: "btn btn-primary"

app/views/medications/edit.html.haml
.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              = "Edit #{@medication.name}"
        = link_to "Cancel", medication_path(@medication)

    = render 'form'

app/views/medications/index.html.haml
= form_tag medications_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form-control", id: "srch-term", placeholder: "Search Medications"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %i.glyphicon.glyphicon-search

.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              Medications
          = link_to "Add New Medication", new_medication_path
.row          
  - @medications.each do |medication|
    .col-md-4.text-center
      .list-group-item
        %strong 
          Medication Name:
        = link_to medication.name, medication_path(medication)
        %br/
        %strong 
          Company:
        = medication.company
        %br
        = link_to "Edit Medication", edit_medication_path(medication)
        |
        \#{link_to "Delete Medication", medication_path(medication), method: :delete}
      %br

app/views/medications/new.html.haml
.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              New Medication
        = link_to "Cancel", clinics_path
    =render 'form'

app/views/medications/show.html.haml
.col-md-12
  .col-md-4.col-md-offset-4
    .jumbotron
      .text-center
        %strong
          %h3
            %u
              = @medication.name
        = link_to "Edit Medication", edit_medication_path(@medication)
        |
        = link_to "Delete Medication",  medication_path(@medication), method: :delete
%div.col-md-4.col-md-offset-4
  .list-group-item
    %strong Medication Name:
    = @medication.name
    %br/
    %strong Company:
    = @medication.company
    %br/
    %strong Adverse Reactions:
    = @medication.adverse_reactions
    %br/
    %strong Generic Options Available:
    = @medication.has_generic?
    %br/
  %br
  .list-group-item
    .text-center
      %strong Patient Users:
    %ul
      - @patients.each do |patient|
        %li
          = patient.last_name
          = patient.first_name