config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/about'

    resources :clinics do
      member do
      post :create_doctor
      delete :destroy_doctor
    end
      resources :patients do
        member do
          post :create_doctor
          delete :destroy_doctor
          patch :wait_patient
          patch :to_doctor_patient
          patch :to_xray_patient
          patch :to_surgery_patient
          patch :to_pay_bill_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :clinic
  has_many :patient_medications
  has_many :medications, through: :patient_medications
  has_many :doctors, as: :doctorable

  BLOOD_TYPE_OPTIONS = [
    ["O-", "O-"],
    ["O+", "O+"],
    ["A-", "A-"],
    ["A+", "A+"],
    ["B-", "B-"],
    ["B+", "B+"],
    ["AB-", "AB-"],
    ["AB+", "AB+"],
  ]

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true
  validates :gender, presence: true
  validates :blood_type, presence: true
  validate :at_least_10
  def at_least_10
    if self.date_of_birth
        errors.add(:date_of_birth, 'Error. Patient must be at least 10 years old') if self.date_of_birth > 10.years.ago.to_date  
    end
  end

  include Workflow
  workflow do
    state :waiting_room do
      event :to_doctor, transitions_to: :doctor_checkup
      event :to_xray, transitions_to: :xray
      event :to_surgery, transitions_to: :surgery
      event :leave, transitions_to: :left
    end
    
    state :doctor_checkup do
      event :to_xray, transitions_to: :xray
      event :to_surgery, transitions_to: :surgery
      event :to_pay_bill, transitions_to: :pay_bill
    end

    state :xray do
      event :to_doctor, transitions_to: :doctor_checkup
      event :to_surgery, transitions_to: :surgery
      event :to_pay_bill, transitions_to: :pay_bill
    end

    state :surgery do
      event :to_doctor, transitions_to: :doctor_checkup
      event :to_xray, transitions_to: :xray
      event :to_pay_bill, transitions_to: :pay_bill
    end

    state :pay_bill do
      event :leave, transitions_to: :left
    end

    state :left do
      event :wait, transitions_to: :waiting_room
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [
    :show,
    :edit,
    :update,
    :destroy,
    :wait_patient
  ]

  def index
    set_clinic
    @patients = if !params[:q].blank?
      Patient.where("first_name LIKE ? OR last_name LIKE ? OR date_of_birth LIKE ? OR description LIKE ? OR gender LIKE ? OR blood_type LIKE ? OR workflow_state LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%")
    else
      Patient.all
    end
  end

  def show
   @clinic = Clinic.find params[:clinic_id]
   @patient = Patient.find params[:id]
   @medications = @patient.medications
   @doctor = Doctor.new
   @doctors = @patient.doctors
  end


  def new
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.new
    @medications = Medication.all
  end

  def create
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.create patient_params
    @medications = Medication.all
    if @patient.save
      flash[:notice] = 'Patient info was successfully saved.'
      redirect_to clinic_path(@clinic)
    else
      flash[:notice] = 'Patient info was NOT successfully saved.'
      render :new
    end
  end

  def edit
    @clinic = Clinic.find params[:clinic_id]
    @medications = Medication.all
    @patient = @clinic.patients.find params[:id]
  end

  def update
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @medications = Medication.all
    if @patient.update_attributes patient_params
      flash[:notice] = 'Patient info was successfully updated.'
      redirect_to clinic_path(@clinic)
    else
      flash[:notice] = 'Patient info was NOT successfully updated.'
      render :edit
    end
  end

  def destroy
    @patient = Patient.find params[:id]
    @clinic = Clinic.find params[:clinic_id]
    if @patient.destroy
      flash[:notice] = 'Patient info was successfully deleted.'
      redirect_to clinic_path(@clinic)
    else
      flash[:notice] = 'Patient info was NOT successfully deleted.'
    end
  end

  def create_doctor
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id] 
    @doctor = @patient.doctors.create doctor_params
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def destroy_doctor
    @doctor = Doctor.find params[:id]
    @doctor.destroy
    redirect_to clinic_patient_path(@doctor.doctorable.clinic, @doctor.doctorable)
  end

  def wait_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.wait!
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def to_doctor_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_doctor!
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def to_xray_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_xray!
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def to_surgery_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_surgery!
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def to_pay_bill_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.to_pay_bill!
    redirect_to clinic_patient_path(@clinic, @patient)
  end

  def leave_patient
    @clinic = Clinic.find params[:clinic_id]
    @patient = @clinic.patients.find params[:id]
    @patient.leave!
    redirect_to clinic_patient_path(@clinic, @patient)
  end

private
  def patient_params
    params.require(:patient).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :description,
        :gender,
        :blood_type,
        medication_ids: []
      ) 
  end

  def set_clinic
    @clinic = Clinic.find(params[:clinic_id])
  end

  def set_patient
    @patient = Patient.find params[:id]
  end

  def doctor_params
  params.require(:doctor).permit(
    :doctor_name
    )
  end

end

app/helpers/patients_helper.rb
module PatientsHelper

  def workflow_state_helper(patient)
    if patient.workflow_state == "waiting_room"
      "Patient is in waiting room."
    elsif patient.workflow_state == "doctor_checkup"
      "Patient is with the doctor."
    elsif patient.workflow_state == "xray"
      "Patient is in xray."
    elsif patient.workflow_state == "surgery"
      "Patient is in surgery."
    elsif patient.workflow_state == "pay_bill"
      "Patient is paying bill."
    elsif patient.workflow_state == "left"
      "Patient has left."
    end
  end



#for review
# def patient_state?(patient)
#     array_of_links = []
#     waiting_room_links = [
#       (link_to "Doctor Check-Up", check_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "X-Ray room", examine_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Surgery", operate_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Discharged", leave_patient_clinic_patient_path(@clinic, @patient), method: :patch)
#     ]
#     doctor_links = [
#       (link_to "X-Ray room", examine_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Surgery", operate_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Billing", pay_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#     ]
#     xray_links = [
#       (link_to "Doctor Check-Up", check_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Surgery", operate_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Billing", pay_patient_clinic_patient_path(@clinic, @patient), method: :patch)
#     ]
#     surgery_links = [
#       (link_to "Doctor Check-Up", check_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "X-Ray room", examine_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#       (link_to "Billing", pay_patient_clinic_patient_path(@clinic, @patient), method: :patch),
#     ]
#     paying_links = [
#       (link_to "Discharged", leave_patient_clinic_patient_path(@clinic, @patient), method: :patch)
#     ]
#     # if the patient has the checkup event on it
#       # array_of_links.push(checkup link_to)

#     # if the patient has the xray event on it
#       # array_of_links.push(xray link_to)

#     if patient.waiting_room?
#       array_of_links.push(waiting_room_links)
#       return array_of_links.join(' | ').html_safe
#     elsif patient.doctor?
#       array_of_links.push(doctor_links)
#       return array_of_links.join(' | ').html_safe
#     elsif patient.xray?
#       array_of_links.push(xray_links)
#       return array_of_links.join(' | ').html_safe
#     elsif patient.surgery?
#       array_of_links.push(surgery_links)
#       return array_of_links.join(' | ').html_safe
#     elsif patient.paying?
#       array_of_links.push(paying_links)
#       return array_of_links.join(' | ').html_safe
#     end
#   end



end

app/views/patients/_form.html.haml
= form_for([@clinic, @patient]) do |f|
  - if @patient.errors.any?
    %p#notice=notice
    - @patient.errors.full_messages.each do |message|
      = message
      %br/
%br/
= form_for [@clinic, @patient] do |f|
  %strong= f.label :first_name
  = f.text_field :first_name
  %br/
  %strong= f.label :last_name
  = f.text_field :last_name
  %br/
  %strong= f.label :date_of_birth
  = f.date_field :date_of_birth, :start_year => Date.today.year - 110, :end_year => Date.today.year
  %br/
  %strong= f.label :description
  = f.text_field :description
  %br/
  %strong= f.label :gender
  = f.radio_button(:gender, "male")
  = f.label(:gender, "male")
  = f.radio_button(:gender, "female")
  = f.label(:gender, "female")
  %br/
  %strong= f.label :blood_type
  = f.select :blood_type, options_for_select(Patient::BLOOD_TYPE_OPTIONS, f.object.blood_type), include_blank: "---Select---"
  %br/
  - @medications.each do |medication|
    = check_box_tag 'patient[medication_ids][]', medication.id, @patient.medications.include?(medication)
    = medication.name
  %br/
  = f.submit
= link_to "Cancel", clinic_path(@clinic)
= link_to "Return to Main", root_path

app/views/patients/edit.html.erb
<h1>Edit Patient Info</h1>
<%= render 'form' %>

app/views/patients/index.html.haml
%p#notice= notice

= form_tag clinic_patients_path, method: :get, class: "navbar-form", role: "search" do
  .input-group
    = text_field_tag 'q', params[:q], class: "form_control", id: "srch-term", placeholder: "Search Patients"
    .input-group-btn
      %button.btn.btn-default{:style => "width:40px;"}
        %i.glyphicon.glyphicon-search


%h1
  = "Patients at Hospital: #{@clinic.name}"
%br
%br
%ul
  Patient Names:
  %br
  %br
  - @patients.each do |patient|
    %li
      = link_to patient.first_name + ' ' + patient.last_name, clinic_patient_path(@clinic, patient)





/ %h1 Patients
/ %br/
/ = link_to "Create New Patient Information", new_patient_path
/ %br/
/ %ul
/   - @patients.each do |patient|
/     %li
/       %strong Patient Name:
/       = link_to patient.last_name + ", " + patient.first_name, patient_path(patient)
/       %br/
/       %strong DOB:
/       = patient.date_of_birth
/       %br/
/       %strong Description:
/       = patient.description
/       %br/
/       %strong Gender:
/       = patient.gender
/       %br/
/       %strong Blood Type:
/       = patient.blood_type
/       %br/
/       = link_to "Edit Patient", edit_patient_path(patient)
/       |
/       \#{link_to "Delete Patient", patient_path(patient), method: :delete}
/     %br/
/ = link_to "Return to Main", root_path

app/views/patients/new.html.erb
<h1>Enter Patient Information</h1>

<%= render 'form' %>

app/views/patients/show.html.haml
.col-md-4.col-md-offset-4
  .jumbotron
    .text-center
      %strong
        %h3
          %u
            Patient:
            = @patient.last_name + ", " + @patient.first_name
        = "Patient Status: "
        = workflow_state_helper(@patient)
      %br
      -if @patient.workflow_state == "waiting_room"
        = link_to "To Doctor", to_doctor_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To X-ray", to_xray_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To Surgery", to_surgery_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "Leave", leave_patient_clinic_patient_path(@clinic, @patient), method: :patch
      -elsif @patient.workflow_state == "doctor_checkup"
        = link_to "To X-ray", to_xray_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To Surgery", to_surgery_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To Pay Bill", to_pay_bill_patient_clinic_patient_path(@clinic, @patient), method: :patch
      -elsif @patient.workflow_state == "xray"
        = link_to "To Doctor", to_doctor_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To Surgery", to_surgery_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To Pay Bill", to_pay_bill_patient_clinic_patient_path(@clinic, @patient), method: :patch
      -elsif @patient.workflow_state == "surgery"
        = link_to "To Doctor", to_doctor_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To X-ray", to_xray_patient_clinic_patient_path(@clinic, @patient), method: :patch
        |
        = link_to "To Pay Bill", to_pay_bill_patient_clinic_patient_path(@clinic, @patient), method: :patch
      -elsif @patient.workflow_state == "pay_bill"
        = link_to "Leave", leave_patient_clinic_patient_path(@clinic, @patient), method: :patch
      -elsif @patient.workflow_state == "left"
        = link_to "Back in to Waiting Room", wait_patient_clinic_patient_path(@clinic, @patient), method: :patch
      %br
      %br
      = link_to "Edit Patient/Medication", edit_clinic_patient_path(@clinic, @patient)
      |
      = link_to "Delete Patient", clinic_patient_path(@clinic, @patient), method: :delete
      %br
      = link_to "Return to Clinic", clinic_path(@clinic)
      |
      = link_to "Return to Main", root_path
      %br
  %p{class: "text-left"}
    .list-group-item
      %strong DOB:
      = @patient.date_of_birth
      %br/
      %strong Symptoms:
      = @patient.description
      %br/
      %strong Gender:
      = @patient.gender
      %br/
      %strong Blood Type:
      = @patient.blood_type
      %br/
      
    %br/
    .list-group-item
      .text-center
        .h4
          %strong Patient Medications:
      %ul
        - @medications.each do |medication|
          %li
            = link_to medication.name, medication_path(medication)
    %br
    .list-group-item
      .text-center
        .h4
          %strong Patient Doctor(s) Name:
      %br
      %ul
        - @doctors.each do |doctor|
          %li
            = doctor.doctor_name
            = link_to "Remove Doctor", destroy_doctor_clinic_patient_path(@patient, doctor), method: :delete

      .text-center
        = form_for @doctor, url: create_doctor_clinic_patient_path(@clinic, @patient) do |f|
          .form_group
            = f.label :doctor_name
            = f.text_area :doctor_name, class: "form-control"
            %br
            = f.submit "Add Doctor", class: "btn btn-primary"