config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get 'home/about'

    resources :clinics do
      member do
      post :create_doctor
      delete :destroy_doctor
    end
      resources :patients do
        member do
          post :create_doctor
          delete :destroy_doctor
          patch :wait_patient
          patch :to_doctor_patient
          patch :to_xray_patient
          patch :to_surgery_patient
          patch :to_pay_bill_patient
          patch :leave_patient
        end
      end
    end
    resources :medications

end

app/views/layouts/application.html.haml
%html
  %head
    %title HPMTS
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    / Fixed navbar
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => "#"} H.P.M.T.S.
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li{class: active_link(root_path)}
              = link_to "Home", root_path
            %li{class: active_link(home_about_path)}
              = link_to "About", home_about_path
            %li
              %a{:href => "mailto: hospital@test.com?subject=Employee Input", :target => "_blank"} Contact
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Navigate
                %span.caret
              %ul.dropdown-menu{:role => "menu"}
                %li
                  = link_to "Clinics Main", clinics_path
                %li
                  = link_to "Medications Main", medications_path
          %ul.nav.navbar-nav.navbar-right
            HOSPITAL / PATIENT / MEDICATION TRACKING SYSTEM
        / /.nav-collapse
    / Begin page content
    .container
      = yield
    /
      Bootstrap core JavaScript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}